### ISSUE TITLE
react icons

### ISSUE THREAD

**Issue by alexanderspevak** [TechnologyGeek12/react-draggable-resizable-modal#1]
Hi, react icons is missing from dependencies. When installed it does not use correct path to it.

**Comment by TechnologyGeek12** [comment]
Hi,
Thanks for your precious time and raising this issue, but i didn't used any react icon dependency for this package so it is not required, you need to use font-awesome icons as described in REDME.
If you still facing some issue regarding it so could you please share some video or codepen link of your code to get more information about your issue

**Comment by TechnologyGeek12** [comment]
Hi,
Thanks for your precious time and raising this issue. As this dependency is already added in package with version  ^2.2.7.
So please try to reinstall it and it should work fine.

**Comment by TechnologyGeek12** [comment]
Hi,
Hope you fixed the issue and working fine.
closing this issue for now, due to inactivity for so long.

Thanks.
